name: Deploy Static Files to GitHub Pages

on:
  push:
    branches:
      - main  # จะทำงานเมื่อมี push ไปยัง branch `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t static-site .

      # Step 3: Run container to test (optional)
      - name: Run container locally for testing
        run: |
          docker run -d -p 8080:80 --name static-container static-site
          echo "Container is running at http://localhost:8080"

      # Step 4: Deploy to GitHub Pages
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./  # ระบุโฟลเดอร์ที่มี static files (ปกติคือ root directory)

